Set up hello rails project
Becky449/hello-rails-react pull request #1
Opened 2023-06-17 09:23 UTC by Becky449

- - Create a new Rails app called 'hello-rails-react'.
- Use the command rails new -j webpack my_new_rails_app as described in the previous lesson's tutorial.
- Verify that the jsbundling-rails gem is added to your Gemfile.
- Initialize your project with Git.
- Install needed node dependencies as described in the previous lesson's tutorial.
- Create a babel.config.js in the root folder of your project as described in the previous lesson's tutorial.
- Update webpack.config.js to include the babel loader as described in the previous lesson's tutorial.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
- Create a static view that will be the root of your app.
- Create the App component with react-router and render it in your static view.
- Create the Greeting component that will display a greeting. Set it up as a route in your App component.
- Create a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
- Display the random greeting in your Greeting component.

2023-06-17 09:52 UTC, rloterh reviewed
Hi Becky, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented; Ensure that provided placeholder texts/ guide instructions are removed and/or replaced with appropriate contents applicable under each section of your ReadMe. 

**Kindly remove/update all aspects similar to the underlined:**
![image](https://github.com/Becky449/hello-rails-react/assets/12745474/fe98c516-6153-4b9e-a57a-21fc135c8f9d)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-17 12:32 UTC, cynthiainga requested changes
Hi @Becky449, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- [ ] No linters errors ✔️ 
- [ ] There is a `Greeting` component ✔️ 
- [ ] Correct Gitflow ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can get the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 12:32 UTC, cynthiainga commented on README.md
> +```
- [ ] Kindly pay more intention to the information you give in your README file, please kindly fix this command link 🙃

2023-06-17 12:32 UTC, cynthiainga commented on app/views/layouts/application.html.erb
> +    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
- [ ] When I run the app I get an error and we can test the project, please kindly fix that 🙏🏾 

<img width="735" alt="Screenshot 2023-06-17 at 15 09 25" src="https://github.com/Becky449/hello-rails-react/assets/74501523/d9c92c2c-a913-4523-b277-18ec0fa24dcf">

2023-06-30 07:03 UTC, addod19 requested changes
### Hi @Becky449, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [ ] Nice job with this project :rocket: 


 ## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be better if we are able to run the app with the `./bin/dev` command
![Screenshot from 2023-06-30 06-57-34](https://github.com/Becky449/hello-rails-react/assets/46388113/fbd648e8-a8b7-493c-bcce-60c851b7020a)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 07:05 UTC, Becky449 commented
Hello, I am able to run the ./bin/dev on my end. This is the screenshot 
![rails-react](https://github.com/Becky449/hello-rails-react/assets/82038825/a1e624d0-4fcc-4f88-85e6-99bcc646f5d3)

2023-07-01 07:42 UTC, Felix45 requested changes
Hi @Becky449, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 <img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] No linter errors :white_check_mark: 
- [x] App Models set up correctly :white_check_mark:   
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:  

## Required Changes ♻️
- [ Required ] As mentioned by the previous reviewer, please make sure that running the `./bin/dev` command on the terminal runs and starts your application. Please see how you can set up your application to run with this command in this article [Click here >>](https://betterprogramming.pub/react-with-rails-2022-bd28e1fcd355#ad0a)

## Error
![Screenshot from 2023-07-01 10-37-40](https://github.com/Becky449/hello-rails-react/assets/16392046/a5f600ca-bf2d-4ac9-a55e-398d73bd15f9)
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 13:11 UTC, Becky449 commented
I have done my best to implement the changes on this project and the API works as per this image 
![api2](https://github.com/Becky449/hello-rails-react/assets/82038825/de7b2f37-6f1a-4cc8-a329-b39750153ce0)
@addod19 @rloterh @Felix45 or @cynthiainga  please review my project. Thanks in advance

2023-07-01 15:02 UTC, sumairq approved these changes
### Hi @Becky449 , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 15:09 UTC, merged